import { Reel, CandidateRecommendation, InteractionState } from './types';

export const REELS: Reel[] = [
  {
    id: 'reel-1',
    title: 'When Java Code Finally Works',
    category: 'Programming Meme',
    topics: ['Java', 'Programming', 'Developer Humor'],
    primaryTopic: 'Software Engineering',
    secondaryTopics: ['Java', 'Programming', 'Developer Humor'],
    technologyDomain: 'Software Engineering',
    context: 'A humorous take on the frustration of debugging Java code, relatable to developers.',
    intent: 'Entertainment',
    difficulty: 'Beginner',
    educationalValue: 45,
    careerRelevance: 75,
    entertainmentValue: 92,
    hypeScore: 5,
    qualityStatus: 'ACCEPTED',
  },
  {
    id: 'reel-2',
    title: 'Day in the Life of a Software Engineer',
    category: 'Career',
    topics: ['Software Engineering', 'Developer Lifestyle', 'Programming Career'],
    primaryTopic: 'Software Engineering',
    secondaryTopics: ['Developer Lifestyle', 'Programming Career', 'Software Engineering'],
    technologyDomain: 'Software Engineering',
    context: 'Showcases the daily routine and responsibilities of a working software engineer.',
    intent: 'Educational',
    difficulty: 'Beginner',
    educationalValue: 70,
    careerRelevance: 90,
    entertainmentValue: 80,
    hypeScore: 12,
    qualityStatus: 'ACCEPTED',
  },
  {
    id: 'reel-3',
    title: 'Coding Interview Be Like',
    category: 'Programming Meme',
    topics: ['Coding Interviews', 'DSA', 'Software Engineering'],
    primaryTopic: 'Software Engineering',
    secondaryTopics: ['Coding Interviews', 'DSA', 'Software Engineering'],
    technologyDomain: 'Software Engineering',
    context: 'A comedic sketch about the pressure and absurdity of technical coding interviews.',
    intent: 'Entertainment',
    difficulty: 'Intermediate',
    educationalValue: 50,
    careerRelevance: 85,
    entertainmentValue: 88,
    hypeScore: 8,
    qualityStatus: 'ACCEPTED',
  },
  {
    id: 'reel-4',
    title: 'MacBook vs Windows Laptop for Developers',
    category: 'Hardware',
    topics: ['Laptop', 'Development', 'Hardware', 'Programming'],
    primaryTopic: 'Developer Hardware',
    secondaryTopics: ['Laptop', 'Development', 'Hardware', 'Programming'],
    technologyDomain: 'Hardware',
    context: 'Compares MacBook and Windows laptops from a developer productivity perspective.',
    intent: 'Educational',
    difficulty: 'Beginner',
    educationalValue: 65,
    careerRelevance: 60,
    entertainmentValue: 75,
    hypeScore: 15,
    qualityStatus: 'ACCEPTED',
  },
  {
    id: 'reel-5',
    title: 'New Gaming Setup',
    category: 'Gaming',
    topics: ['Gaming', 'PC', 'RGB', 'Hardware'],
    primaryTopic: 'Gaming',
    secondaryTopics: ['Gaming', 'PC', 'RGB', 'Hardware'],
    technologyDomain: 'Gaming',
    context: 'Showcases a high-end gaming PC build with RGB lighting.',
    intent: 'Entertainment',
    difficulty: 'Beginner',
    educationalValue: 20,
    careerRelevance: 10,
    entertainmentValue: 85,
    hypeScore: 25,
    qualityStatus: 'ACCEPTED',
  },
  {
    id: 'reel-6',
    title: '10 AI Tools That Will Get You a Job',
    category: 'AI / Career',
    topics: ['AI', 'Career', 'Job Search'],
    primaryTopic: 'AI',
    secondaryTopics: ['AI', 'Career', 'Job Search'],
    technologyDomain: 'AI',
    context: 'Claims that using certain AI tools will guarantee employment.',
    intent: 'Promotional',
    difficulty: 'Beginner',
    educationalValue: 22,
    careerRelevance: 40,
    entertainmentValue: 60,
    hypeScore: 91,
    qualityStatus: 'REJECTED',
    qualityReason: 'High hype and unrealistic career-outcome claim.',
  },
  {
    id: 'reel-7',
    title: 'What Happens During a DDoS Attack?',
    category: 'Cybersecurity',
    topics: ['Cybersecurity', 'Networking', 'DDoS'],
    primaryTopic: 'Cybersecurity',
    secondaryTopics: ['Cybersecurity', 'Networking', 'DDoS'],
    technologyDomain: 'Cybersecurity',
    context: 'Explains the mechanics of a Distributed Denial of Service attack.',
    intent: 'Educational',
    difficulty: 'Intermediate',
    educationalValue: 78,
    careerRelevance: 55,
    entertainmentValue: 70,
    hypeScore: 10,
    qualityStatus: 'ACCEPTED',
  },
  {
    id: 'reel-8',
    title: 'Why Developers Learn Cloud Computing',
    category: 'Cloud',
    topics: ['Cloud', 'AWS', 'Software Engineering', 'Career'],
    primaryTopic: 'Cloud Computing',
    secondaryTopics: ['Cloud', 'AWS', 'Software Engineering', 'Career'],
    technologyDomain: 'Cloud',
    context: 'Explains the career benefits of learning cloud computing as a developer.',
    intent: 'Educational',
    difficulty: 'Intermediate',
    educationalValue: 72,
    careerRelevance: 80,
    entertainmentValue: 65,
    hypeScore: 18,
    qualityStatus: 'ACCEPTED',
  },
];

export const CANDIDATES: CandidateRecommendation[] = [
  {
    id: 'cand-1',
    title: 'How Developers Choose the Right Laptop for Coding',
    category: 'Hardware',
    topic: 'Developer Hardware',
    difficulty: 'Beginner',
    educationalValue: 80,
    careerRelevance: 65,
    contentQuality: 85,
    novelty: 40,
    engagementPotential: 78,
    hypeScore: 10,
  },
  {
    id: 'cand-2',
    title: 'Understanding REST APIs',
    category: 'Web Development',
    topic: 'Web Development',
    difficulty: 'Intermediate',
    educationalValue: 88,
    careerRelevance: 90,
    contentQuality: 90,
    novelty: 50,
    engagementPotential: 70,
    hypeScore: 5,
  },
  {
    id: 'cand-3',
    title: 'DSA Interview Preparation',
    category: 'DSA',
    topic: 'Data Structures & Algorithms',
    difficulty: 'Advanced',
    educationalValue: 92,
    careerRelevance: 95,
    contentQuality: 88,
    novelty: 35,
    engagementPotential: 82,
    hypeScore: 8,
  },
  {
    id: 'cand-4',
    title: 'System Design Basics',
    category: 'HLD',
    topic: 'System Design',
    difficulty: 'Advanced',
    educationalValue: 90,
    careerRelevance: 92,
    contentQuality: 87,
    novelty: 55,
    engagementPotential: 75,
    hypeScore: 6,
  },
  {
    id: 'cand-5',
    title: 'Git and GitHub Workflow',
    category: 'Programming',
    topic: 'Version Control',
    difficulty: 'Beginner',
    educationalValue: 85,
    careerRelevance: 88,
    contentQuality: 86,
    novelty: 30,
    engagementPotential: 72,
    hypeScore: 4,
  },
  {
    id: 'cand-6',
    title: 'Cloud Computing for Developers',
    category: 'Cloud',
    topic: 'Cloud Computing',
    difficulty: 'Intermediate',
    educationalValue: 84,
    careerRelevance: 86,
    contentQuality: 83,
    novelty: 45,
    engagementPotential: 76,
    hypeScore: 12,
  },
  {
    id: 'cand-7',
    title: 'How Software Engineering Teams Work',
    category: 'Career',
    topic: 'Software Engineering',
    difficulty: 'Beginner',
    educationalValue: 82,
    careerRelevance: 89,
    contentQuality: 84,
    novelty: 50,
    engagementPotential: 80,
    hypeScore: 7,
  },
  {
    id: 'cand-8',
    title: 'How AI Coding Assistants Improve Developer Productivity',
    category: 'AI',
    topic: 'AI Tools',
    difficulty: 'Intermediate',
    educationalValue: 82,
    careerRelevance: 78,
    contentQuality: 85,
    novelty: 70,
    engagementPotential: 84,
    hypeScore: 18,
  },
];

export const DEMO_INTERACTIONS: Record<string, InteractionState> = {
  'reel-1': { watchPercent: 95, like: true, save: true, share: false, rewatch: true, comment: false, skip: false },
  'reel-2': { watchPercent: 92, like: true, save: true, share: false, rewatch: true, comment: false, skip: false },
  'reel-3': { watchPercent: 90, like: true, save: false, share: false, rewatch: true, comment: false, skip: false },
  'reel-4': { watchPercent: 87, like: true, save: true, share: false, rewatch: false, comment: false, skip: false },
  'reel-5': { watchPercent: 18, like: false, save: false, share: false, rewatch: false, comment: false, skip: false },
  'reel-6': { watchPercent: 60, like: false, save: false, share: false, rewatch: false, comment: false, skip: false },
  'reel-7': { watchPercent: 45, like: false, save: false, share: false, rewatch: false, comment: false, skip: false },
  'reel-8': { watchPercent: 70, like: true, save: false, share: false, rewatch: false, comment: false, skip: false },
};

export const EMPTY_INTERACTIONS: Record<string, InteractionState> = REELS.reduce(
  (acc, reel) => ({
    ...acc,
    [reel.id]: { watchPercent: 0, like: false, save: false, share: false, rewatch: false, comment: false, skip: false },
  }),
  {}
);

export const COLD_START_OPTIONS = [
  'AI',
  'DSA',
  'Java',
  'Cybersecurity',
  'Cloud',
  'Hardware',
  'Career',
  'Web Development',
  'Programming',
  'Databases',
];
